import { createRequire } from 'module';
import type { Config } from 'tailwindcss';
const require = createRequire(import.meta.url);

export default {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                lapis: '#07484A',
                mint: '#70908B',
                white: '#FDFBF8',
                'white-blue': '#E0EFF6',
                'darken-white': '#F0F0F0',
                'absolute-white': '#fff',
                'lite-green': '#E0F6F1',
                'lazuli-green': '#CAF3E5',
                skin: '#FFF4E7',
                'dark-skin': '#ada489',
                purple: '#EEEBFF',
                'absolute-black': '#000',
                clay: '#C4C4C4',
                rose: '#F9D9DA',
                'bg-gray': '#888',
                header: '#7070703e',
                'svg-gray': '#6E757E',
                red: '#a83234',
                orange: '#FFC107',
            },
            fontFamily: {
                playfair: ['"Playfair Display"', 'serif'],
                roboto: ['Roboto', 'sans-serif'],
                opensans: ['"Open Sans"', 'sans-serif'],
            },
            fontSize: {
                'placeholder-sm': '18px',
                'placeholder-md': '24px',
            },
            borderRadius: {
                sm: '6px',
                md: '10px',
                lg: '16px',
                xl: '20px',
                '2xl': '24px',
                '3xl': '50px',
            },
            borderWidth: {
                sm: '1px',
            },
            minWidth: {
                sm: '170px',
                md: '230px',
                lg: '270px',
                xl: '288px',
                '2xl': '360px',
                '3xl': '382px',
            },
            maxWidth: {
                sm: '194px',
                md: '400px',
                lg: '578px',
                xl: '790px',
                '2xl': '850px',
                '3xl': '950px',
            },
            width: {
                'slider-sm': '4px',
                'slider-md': '8px',
                'slider-lg': '28px',
                'slider-xl': '80px',
                'slider-2xl': '120px',
                'logo-sm': '104px',
                'logo-md': '144px',
                'el-sm': '40px',
                'el-md': '90px',
                'el-lg': '204px',
                'el-xl': '242px',
                'el-2xl': '288px',
                'el-3xl': '350px',
                'el-4xl': '394px',
                'el-5xl': '460px',
                'el-6xl': '692px',
                'responsive-sm': 'calc(100% - 300px)',
                'responsive-md': 'calc(100% - 80px)',
                'responsive-lg': 'calc(100% - 40px)',
                'responsive-xl': 'calc(100% - 32px)',
                'responsive-viewport-sm': 'calc(100vw - 32px)',
                'responsive-viewport-md': 'calc(100vw - 40px)',
                'responsive-viewport-lg': 'calc(100vw - 80px)',
                'responsive-viewport-xl': 'calc(100vw - 300px)',
                half: '50%',
            },
            minHeight: {
                sm: '210px',
                md: '280px',
                lg: '324px',
                xl: '340px',
                '2xl': '500px',
                '3xl': '540px',
                '4xl': '600px',
            },
            maxHeight: {
                sm: '700px',
            },
            height: {
                'slider-sm': '4px',
                'slider-md': '8px',
                'slider-lg': '60px',
                'slider-xl': '180px',
                'slider-2xl': '580px',
                'logo-sm': '26px',
                'logo-md': '36px',
                'el-sm': '40px',
                'el-md': '120px',
                'el-lg': '149px',
                'el-xl': '268px',
                'el-2xl': '320px',
                'el-3xl': '332px',
                'el-4xl': '400px',
                'el-5xl': '556px',
                'el-6xl': '600px',
                'el-7xl': '640px',
            },
            gap: {
                sm: '10px',
                md: '18px',
                lg: '24px',
                xl: '26px',
                '2xl': '32px',
                '3xl': '40px',
                '4xl': '42px',
                '5xl': '44px',
                '6xl': '50px',
                '7xl': '52px',
                '8xl': '54px',
                '9xl': '58px',
                '10xl': '60px',
                '11xl': '78px',
                '12xl': '100px',
                '13xl': '104px',
            },
            inset: {
                half: '50%',
                'one-third': '33%',
                'two-thirds': '66%',
                nl: '180%',
                'nl-hover': '110%',
                slider: '-2px',
                'el-sm': '-24px',
                'el-md': '16px',
                'el-lg': '20px',
                'el-xl': '40px',
                'el-2xl': '56px',
                'el-3xl': '96px',
            },
            aspectRatio: {
                '9/21': '0.41',
            },
        },
        screens: {
            md: '768px',
            lg: '1024px',
            xl: '1440px',
            '2xl': '1920px',
        },
        padding: {
            '0': '0px',
            'section-sm': '16px',
            'section-md': '20px',
            'section-lg': '26px',
            'section-xl': '40px',
            'section-2xl': '70px',
            'section-3xl': '80px',
            'section-4xl': '90px',
            'section-5xl': '100px',
            'section-6xl': '120px',
            'section-7xl': '150px',
            'section-8xl': '286px',
            'el-sm': '16px',
            'el-md': '20px',
            'el-lg': '24px',
            'el-xl': '30px',
            'el-2xl': '36px',
            'el-3xl': '40px',
            'el-4xl': '44px',
            'el-5xl': '50px',
            'el-6xl': '60px',
            'el-7xl': '74px',
            'el-8xl': '84px',
            'el-9xl': '122px',
            'el-10xl': '150px',
            'el-11xl': '196px',
        },
        margin: {
            none: '0',
            'logo-sm': '-6px',
            'overflow-container-sm': '16px',
            'overflow-container-md': '20px',
            'overflow-container-lg': '40px',
            'overflow-container-xl': '150px',
        },
        contrast: {
            md: '0.8',
        },
        brightness: {
            md: '0.6',
        },
        flexShrink: {
            none: '0',
        },
    },
    plugins: [require('@designbycode/tailwindcss-text-shadow')],
} satisfies Config;
